DROP TABLE IF EXISTS "Users";

DROP TABLE IF EXISTS "Roles";

DROP TABLE IF EXISTS "UserInfo";

DROP TABLE IF EXISTS "Occupations";

DROP TABLE IF EXISTS "Departments";

DROP TABLE IF EXISTS "Statuses";
